import pg from 'pg';
import fs from 'fs';
const env = fs.readFileSync('.env.local','utf8');
env.split('\n').forEach(l=>{const t=l.trim();if(t&&!t.startsWith('#')&&t.includes('=')){const[k,...r]=t.split('=');process.env[k.trim()]=r.join('=').trim();}});
const p = new pg.Pool({connectionString:process.env.DATABASE_URL});
const r = await p.query("SELECT embedding::text FROM document_chunks LIMIT 1");
const arr = JSON.parse(r.rows[0].embedding);
const norm = Math.sqrt(arr.reduce((s,v)=>s+v*v,0));
console.log("dims:", arr.length, "norm:", Math.round(norm*1000)/1000, "first5:", arr.slice(0,5).map(v=>Math.round(v*1000)/1000), "min/max:", Math.min(...arr).toFixed(3), Math.max(...arr).toFixed(3));
await p.end();
