import pg from 'pg';
import fs from 'fs';
const env = fs.readFileSync('.env.local','utf8');
env.split('\n').forEach(l=>{const t=l.trim();if(t&&!t.startsWith('#')&&t.includes('=')){const[k,...r]=t.split('=');process.env[k.trim()]=r.join('=').trim();}});
const p = new pg.Pool({connectionString:process.env.DATABASE_URL});
const { GoogleGenerativeAI } = await import('@google/generative-ai');
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: 'gemini-embedding-001' });
const chunkRow = await p.query("SELECT raw_content, embedding::text FROM document_chunks LIMIT 1");
const stored = JSON.parse(chunkRow.rows[0].embedding);
const txt = chunkRow.rows[0].raw_content;
const r = await model.batchEmbedContents({ requests:[{ content:{parts:[{text:txt}]}, outputDimensionality: 768, taskType: 'RETRIEVAL_DOCUMENT' }] });
const fresh = r.embeddings[0].values;
console.log("stored len:", stored.length, "fresh len:", fresh.length);
console.log("stored first5:", stored.slice(0,5).map(v=>+v.toFixed(3)));
console.log("fresh  first5:", fresh.slice(0,5).map(v=>+v.toFixed(3)));
console.log("stored[100..105]:", stored.slice(100,105).map(v=>+v.toFixed(3)));
console.log("fresh [100..105]:", fresh.slice(100,105).map(v=>+v.toFixed(3)));
// are they element-wise equal?
let eq = stored.length === fresh.length;
for (let i=0; eq && i<stored.length; i++) if (Math.abs(stored[i]-fresh[i])>1e-4) eq=false;
console.log("element-wise equal?", eq);
await p.end();
